services:
  app:
    image: ghcr.io/benediktwerner/lichess-tournament-scheduler:docker
    environment:
      - DATABASE_PATH=/app/db/database.sqlite
    restart: unless-stopped
    volumes:
      - /data/lichess-tournament-scheduler/config:/app/config
      - /data/lichess-tournament-scheduler/db:/app/db
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.tournament-scheduler.rule=Host(`tournament-scheduler.lichess.app`)
      - traefik.http.routers.tournament-scheduler.entrypoints=websecure
      - traefik.http.routers.tournament-scheduler.tls=true
      - traefik.http.routers.tournament-scheduler.tls.certresolver=myresolver
      - traefik.http.services.tournament-scheduler.loadbalancer.server.port=9091

networks:
  frontend:
    external: true
